import { notFound } from 'next/navigation';
import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import { NextIntlClientProvider } from 'next-intl';
import { GlobalContextProvider } from '@/contexts/store';
import Header from '@/templates/Header';

interface LocaleLayoutProps {
  children: ReactNode;
  params: {
    locale: string;
  };
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: LocaleLayoutProps) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <GlobalContextProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <header>
              <Header type='home' />
            </header>
            <main>{children}</main>
          </NextIntlClientProvider>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
