import { notFound } from 'next/navigation';
import { ReactNode } from 'react';
import type { Metadata } from 'next';
import '@/styles/globals.css';
import { NextIntlClientProvider } from 'next-intl';
import { GlobalContextProvider } from '@/contexts/Font';
import Header from '@/templates/Header';
import { lato, poppins } from '@/fonts';
import { ThemeProvider } from '@/contexts/Theme';
import { ITheme } from '@/@types/Theme';
import Footer from '@/templates/Footer';


interface LocaleLayoutProps {
  children: ReactNode;
  params: {
    locale: string;
    theme: ITheme
  };
}


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: LocaleLayoutProps) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${lato.variable} ${poppins.variable} wrapper`}>
        <ThemeProvider>
          <GlobalContextProvider>
            <NextIntlClientProvider locale={locale} messages={messages}>
              <header>
                <Header type='home' />
              </header>
              <main>{children}</main>
              <footer><Footer /></footer>
            </NextIntlClientProvider>
          </GlobalContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
